### ISSUE TITLE
Integrate Camunda-commons-ui

### ISSUE THREAD

**Issue by Ofenlord** [camunda/camunda-commons-ui#1]
Hi,
i want to integrate the bpmn-viewer in my grails project. i installed node.js and grunt and build camunda-commons-ui, but i don't know how i can use it. i am a student with less experience in grunt and build tools. Normally there are jar packages or such a things.
Can you help me out?

Greetings

**Comment by SebastianStamm** [comment]
I am not a grails expert, but basically you need to have a website with angularjs and load the bpmn-viewer widget with requirejs. The bpmn-viewer widget itself is an angular directive.

The test-page shows an example how you can integrate the bpmn-viewer widget in a website: https://github.com/camunda/camunda-commons-ui/blob/master/lib/widgets/bpmn-viewer/test/cam-widget-bpmn-viewer.spec.html#L191-L206
